# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

alfak2_graph_posterior_cpp <- function(karyotypes, edge_from, edge_to, edge_weight, anchor_index, anchor_mean, anchor_var, lambda_l_grid, lambda_e_grid, sigma_obs_grid, eps = 1e-5) {
    .Call(`_alfak2_alfak2_graph_posterior_cpp`, karyotypes, edge_from, edge_to, edge_weight, anchor_index, anchor_mean, anchor_var, lambda_l_grid, lambda_e_grid, sigma_obs_grid, eps)
}

alfak2_parse_karyotypes_cpp <- function(labels) {
    .Call(`_alfak2_alfak2_parse_karyotypes_cpp`, labels)
}

alfak2_stringify_karyotypes_cpp <- function(karyotypes) {
    .Call(`_alfak2_alfak2_stringify_karyotypes_cpp`, karyotypes)
}

alfak2_build_graph_cpp <- function(labels, y0, y1, beta = 0.00005, transition_kernel = "exact", shell_depth = 2L, min_cn = 0L, max_cn = 5L, max_nodes = 5000L) {
    .Call(`_alfak2_alfak2_build_graph_cpp`, labels, y0, y1, beta, transition_kernel, shell_depth, min_cn, max_cn, max_nodes)
}

alfak2_simulate_counts_cpp <- function(karyotypes, labels, fitness, beta = 0.00005, dt = 1.0, n0 = 500L, n1 = 500L, detection_threshold = 1L, dropout_prob = 0.0, seed = 1L, init_concentration = 1.5, overdispersion = 0.0) {
    .Call(`_alfak2_alfak2_simulate_counts_cpp`, karyotypes, labels, fitness, beta, dt, n0, n1, detection_threshold, dropout_prob, seed, init_concentration, overdispersion)
}

alfak2_pij_cpp <- function(parent_cn, child_cn, beta) {
    .Call(`_alfak2_alfak2_pij_cpp`, parent_cn, child_cn, beta)
}

alfak2_transition_operator_cpp <- function(karyotypes, beta = 0.00005, transition_kernel = "exact") {
    .Call(`_alfak2_alfak2_transition_operator_cpp`, karyotypes, beta, transition_kernel)
}

